name: CI/CD Pipeline for AI Agent

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate:
    name: Validate Code & JSON
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      # Validate file JSON so với schema (sử dụng ajv-cli)
      - name: Validate JSON Config
        run: npx ajv validate -s schema/agent-schema.json -d agent-config.json

      # Chạy lint để kiểm tra chất lượng code
      - name: Run Lint
        run: npm run lint

  test:
    name: Run Unit Tests & Test Cases
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      # Chạy unit test (ví dụ sử dụng Jest)
      - name: Run Unit Tests
        run: npm run test:unit

      # Chạy test cases (có thể là integration tests, scenario tests, …)
      - name: Run Test Cases
        run: npm run test:cases
